name: bootcamp_duygudas_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.6
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  # http: ^0.13.6
  json_annotation: ^4.8.1
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  dialog_flowtter: ^0.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  table_calendar: ^3.1.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/duygudas-431314-d385b1072592.json